from nutriplan.my_models.MyUser import *
from nutriplan.my_models.Food import *
from nutriplan.my_models.Plan import *
from nutriplan.my_models.Day import *
from nutriplan.my_models.Meal import *
from nutriplan.my_models.MealsInDay import *
from nutriplan.my_models.DayHistory import *
from nutriplan.my_models.MealStatus import *
from nutriplan.my_models.Tag import *
from nutriplan.my_models.HasTag import *
from nutriplan.my_models.RatePlan import *
from nutriplan.my_models.RateNutri import *
from nutriplan.my_models.Form import *
from nutriplan.my_models.FormTags import *
from nutriplan.my_models.FollowingPlan import *
from nutriplan.my_models.Comment import *
from nutriplan.my_models.PlanComment import *
from nutriplan.my_models.NutriComment import *